### ISSUE TITLE
403 forbidden while Update Postmortem

### ISSUE THREAD

**Issue by aensk** [ep4sh/autopsy#4]
Steps to reproduce:
1. Log In
2. Open Postmortem "Autopsy fails due to the db connection malformed credentials"
3. Click on tab "Update"

Actual result: Error 403 forbidden 

Expected result: 
![dd763e720d](https://user-images.githubusercontent.com/98712864/151717364-1f0a9044-5ca2-4bc1-8d91-aea04dc5a176.jpg)

**Comment by ep4sh** [comment]
Hi @aensk, that's correct behavior - you can update only your own postmortems.

I agree, it could confuse a bit, so we can think about not to show such button if you're not a author of the postmortem.
