### ISSUE TITLE
Incorrect layout in mobile resolution

### ISSUE THREAD

**Issue by aensk** [ep4sh/autopsy#5]
Steps to reproduce:

1. Log In
2. Open Dashboard

Actual result: incorrect layout in resolution 991px & lower
Expected result: correct layout in mobile resolution
![1203fdef2f](https://user-images.githubusercontent.com/98712864/151718000-bd2891a0-25aa-4d58-8dcd-89863557bd71.jpg)

**Comment by ep4sh** [comment]
Thank you for bringing this up, I'm not a big expert with adaptive design, nevertheless, it was added to the backlog:
https://trello.com/b/ngqvbNgt/autopsy
