### ISSUE TITLE
The "Notifications?" section of the sidebar is inactive

### ISSUE THREAD

**Issue by aensk** [ep4sh/autopsy#6]
Steps to reproduce:

1. Log In
2. Click the "Notifications?" section of the sidebar

Actual result: section is inactive

Expected result: go to section

**Comment by ep4sh** [comment]
That's right, currently, it's just a stub.

Autopsy is under turbulent development, this task is in the backlog, for now, please check the Trello:
https://trello.com/b/ngqvbNgt/autopsy
