### ISSUE TITLE
To change the avatar, you must re-enter the registration data

### ISSUE THREAD

**Issue by aensk** [ep4sh/autopsy#7]
Steps to reproduce:

1. Log In
2. Click the "Profile" section of the sidebar
3. Click on any other avatar image
4. Press the button "Update Profile"

Actual result: the field "Name" is highlighted with notification, although it has already been entered

Expected result:  avatar image changes
![4661e9358f](https://user-images.githubusercontent.com/98712864/151718716-48a8ac08-e2aa-497c-8606-bb675ac91030.jpg)

**Comment by ep4sh** [comment]
Hi, that's correct. I mean the initial idea was so.

Moreover - you will have to change the entire data in your profile. Would you like to change your face? Please change(apply) your new name, a new face, and your credentials too.

This behavior discourages people from changing unnecessary things and focusing on writing postmortems :)
